--- #YAML:1.0
name: Net-DPAP-Client
version: 0.24
author:
  - Leon Brocard <acme@astray.com>
abstract: Connect to iPhoto shares (DPAP)
license: perl
requires:
  Carp::Assert: 0
  Class::Accessor::Fast: 0
  LWP::Simple: 0
  Net::DAAP::DMAP: 1.20
  URI: 0
provides:
  Net::DPAP::Client:
    file: lib/Net/DPAP/Client.pm
    version: 0.24
  Net::DPAP::Client::Album:
    file: lib/Net/DPAP/Client/Album.pm
  Net::DPAP::Client::Image:
    file: lib/Net/DPAP/Client/Image.pm
generated_by: Module::Build version 0.25
